/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary": "var(--color-primary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-background": "var(--color-on-background)",
        "tertiary-container": "var(--color-tertiary-container)",
        "background": "var(--color-background)",
        "secondary": "var(--color-secondary)",
        "surface-tint": "var(--color-surface-tint)",
        "outline-variant": "var(--color-outline-variant)",
        "error": "var(--color-error)",
        "error-container": "var(--color-error-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-primary": "var(--color-on-primary)",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-error-container": "var(--color-on-error-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface": "var(--color-surface)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "tertiary": "var(--color-tertiary)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-high": "var(--color-surface-container-high)",
        "outline": "var(--color-outline)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "inverse-surface": "var(--color-inverse-surface)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-surface": "var(--color-on-surface)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary": "var(--color-on-secondary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "primary-container": "var(--color-primary-container)",
        "on-error": "var(--color-on-error)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "tertiary-fixed": "var(--color-tertiary-fixed)"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "container-max": "1280px",
        base: "4px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        md: "24px",
        sm: "16px",
        xs: "8px"
      },
      fontFamily: {
        "hero-display-mobile": ["'Playfair Display SC'", "serif"],
        "headline-lg": ["'Playfair Display SC'", "serif"],
        "hero-display": ["'Playfair Display SC'", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["'Playfair Display SC'", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "hero-display-mobile": ["40px", {"lineHeight": "1.1", "letterSpacing": "-1.5px", "fontWeight": "800"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.5px", "fontWeight": "700"}],
        "hero-display": ["56px", {"lineHeight": "1.1", "letterSpacing": "-2px", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
